<x-app-layout>
    <div class="content-header">
        <h1>Health Record Details</h1>
        <p>Submitted on {{ $record->created_at->format('F j, Y, g:i a') }}</p>
    </div>

    @if(session('success'))
        <div class="alert alert-success">{{ session('success') }}</div>
    @endif

    @php
        $aiData = json_decode($record->recommendation, true);
    @endphp

    <div class="card">
        <div class="alert alert-caution" style="display: flex; align-items: flex-start; gap: 1rem;">
            <div>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 256 256"><path d="M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm0,192a88,88,0,1,1,88-88A88.1,88.1,0,0,1,128,216Zm16-40a8,8,0,0,1-8,8,16,16,0,0,1-16-16V128a8,8,0,0,1,0-16,16,16,0,0,1,16,16v40A8,8,0,0,1,144,176ZM112,88a12,12,0,1,1,12,12A12,12,0,0,1,112,88Z"></path></svg>
            </div>
            <div>
                <h4 style="margin: 0 0 0.5rem 0; font-size: 1.1rem;">A Note on AI Suggestions</h4>
                <p style="margin: 0;">The analysis below is generated by AI to provide helpful, general insights. For a complete understanding of your health and for any diagnosis, consulting with your doctor is always the best next step.</p>
            </div>
        </div>

        <h3 style="margin-top: 2rem;">AI Health Analysis</h3>

        @if(isset($aiData['error']))
            <div class="alert alert-danger">
                <p>Could not generate AI analysis for this record.</p>
                <p><small>{{ $aiData['error'] }}</small></p>
            </div>
        @else
            <div class="health-dashboard">
                <!-- Overall Status -->
                <div class="overall-status status-{{ Str::slug($aiData['overall_status'] ?? 'default') }}">
                    <h4>Overall Health Indicator</h4>
                    <p>{{ $aiData['overall_status'] ?? 'N/A' }}</p>
                </div>

                <!-- Individual Metrics Grid -->
                <div class="metrics-grid">
                    @forelse($aiData['metrics'] ?? [] as $metric)
                        <div class="metric-card status-{{ Str::slug($metric['status'] ?? 'default') }}">
                            <h5>{{ $metric['name'] }}</h5>
                            <div class="metric-value">{{ $metric['value'] }}</div>
                            <div class="metric-status">{{ $metric['status'] }}</div>
                        </div>
                    @empty
                        <p>Metric details could not be generated for this record.</p>
                    @endforelse
                </div>

                <!-- Key Advice & Resources -->
                <div class="advice-section">
                    <div class="key-advice">
                        <h5>Key Advice</h5>
                        <ul>
                            @foreach($aiData['key_advice'] ?? [] as $advice)
                                <li>{{ $advice }}</li>
                            @endforeach
                        </ul>
                    </div>
                    <div class="resource-links">
                        <h5>Suggested Resources</h5>
                        <ul>
                             @foreach($aiData['resource_links'] ?? [] as $link)
                                @if(isset($link['url']) && isset($link['title']))
                                    <li><a href="{{ $link['url'] }}" target="_blank">{{ $link['title'] }}</a></li>
                                @endif
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        @endif

        <hr style="margin: 2rem 0;">
        <button onclick="window.print()" class="btn btn-secondary no-print">Print this Record</button>
    </div>
</x-app-layout>